---
- name: Install openconnect and L2TP VPN client for gnome
  ansible.builtin.apt:
    name:
      - network-manager-openconnect
      - network-manager-openconnect-gnome
      - network-manager-l2tp
      - network-manager-l2tp-gnome
