---
- name: Griffin Post-Installation Setup
  hosts: vagrant
  gather_facts: true
  strategy: linear
  become: true
  remote_user: root

  roles:
    - role: post-installation
      tags: post-installation
