#!/bin/bash

commit_msg_file=$1

getJiraTicketNumber() {
    local branchName=$(git branch --show-current)
    echo "$branchName" | grep -o -E '[A-Z]+-[0-9]+'
}

# check if commit message contains just Jira ticket number
# if so, exit with failure

commit_message=$(cat "$1")

# trim all lines that start with a hash
commit_message=$(echo "$commit_message" | sed '/^#/d')

# trim all spaces
commit_message=$(echo "$commit_message" | sed 's/^[ \t]*//;s/[ \t]*$//')

# red color for error message
red='\033[0;31m'

if [ "$commit_message" = "$(getJiraTicketNumber)" ]; then
    echo "${red}Commit message contains just Jira ticket number. Please add more details!"
    exit 1
fi
