#!/bin/bash

commit_msg_file=$1
branch_name=$(git symbolic-ref --short HEAD)
ticket_number=$(echo "$branch_name" | grep -oE '[A-Z]+-[0-9]+')

if [ -n "$ticket_number" ]; then
    commit_message=$(cat "$commit_msg_file")
    # trim all lines that start with a hash
    commit_message=$(echo "$commit_message" | sed '/^#/d')
    # trim all spaces
    commit_message=$(echo "$commit_message" | sed 's/^[ \t]*//;s/[ \t]*$//')

    # If the ticket number is not in the commit message, add it
    if [[ $(echo "$commit_message" | grep -c "$ticket_number") -eq 0 ]]; then
        # Prepend the ticket number to the commit message
        sed -i "1s/^/$ticket_number /" "$commit_msg_file"
    fi
fi
