---
- name: Configure dconf applications
  block:
    - name: Configure guake
      shell: |
        cat ./post-installation/defaults/dconf-settings/apps.guake.ini | dconf load "{{ dconf_guake }}"

    - name: Configure gnome desktop
      shell: |
        cat ./post-installation/defaults/dconf-settings/org.gnome.desktop.ini | dconf load "{{ dconf_org_gnome_desktop }}"


    - name: Configure cinnamon desktop
      shell: |
        cat ./post-installation/defaults/dconf-settings/org.cinnamon.desktop.ini | dconf load "{{ dconf_org_cinnamon_desktop }}"

    - name: Configure nemo
      shell: |
        cat ./post-installation/defaults/dconf-settings/org.nemo.ini | dconf load "{{ dconf_org_nemo }}"

    - name: Configure Linux Mint updates
      shell: |
        cat ./post-installation/defaults/dconf-settings/com.linuxmint.updates.ini | dconf load "{{ dconf_org_com_linuxmint_updates }}"

  become_user: "{{ username }}"
