---
- name: Configure dconf applications
  block:
    - name: Configure guake
      ansible.builtin.shell: |
        cat ./post-installation/defaults/dconf-settings/apps.guake.ini | dconf load "/apps/guake/"

    - name: Configure gnome desktop
      ansible.builtin.shell: |
        cat ./post-installation/defaults/dconf-settings/org.gnome.desktop.ini | dconf load "/org/gnome/desktop/"

    - name: Configure cinnamon desktop
      ansible.builtin.shell: |
        cat ./post-installation/defaults/dconf-settings/org.cinnamon.desktop.ini | dconf load "/org/cinnamon/desktop/"

    - name: Configure nemo
      ansible.builtin.shell: |
        cat ./post-installation/defaults/dconf-settings/org.nemo.ini | dconf load "/org/nemo/"

    - name: Configure Linux Mint updates
      ansible.builtin.shell: |
        cat ./post-installation/defaults/dconf-settings/com.linuxmint.updates.ini | dconf load "/com/linuxmint/updates/"

    - name: Set Adapta-Nokto start menu theme
      ansible.builtin.shell: |
        gsettings set org.cinnamon.theme name "Adapta-Nokto"

  become_user: "{{ username }}"
