---
- name: Ansible delete file wildcard
  find:
    paths: ["{{ download_dir }}"]
    patterns: "^.*$"
    use_regex: true
  register: wildcard_files_to_delete

- name: Ansible remove file wildcard
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ wildcard_files_to_delete.files }}"
