---
- name: Install apt apps - curl, VIm, Terminator, RedShift, htop
  ansible.builtin.apt:
    name:
      - bat
      - curl
      - zip
      - unzip
      - htop
      - libutempter0
      - make
      - shellcheck
      - vim
      - python3-pip
      - jq

# - name: Install SDKMan
#   ansible.builtin.shell: |
#     curl -s "https://get.sdkman.io" | bash
#   become_user: "{{ username }}"
#   become: true

- name: Copy Zscaler root cert to $HOME
  ansible.builtin.copy:
    src: ./defaults/.ZscalerRootCA.crt
    dest: "{{ user_home }}"
    mode: "0644"
  become_user: "{{ username }}"
  become: true

- name: Remove old Volta binary
  ansible.builtin.file:
    path: "/home/{{ username }}/.volta/bin/volta"
    state: absent
  become_user: "{{ username }}"

- name: Install Volta
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl https://get.volta.sh | bash
    executable: /usr/bin/zsh
  become_user: "{{ username }}"
  become: true
  args:
    creates: "/home/{{ username }}/.volta/bin/volta"

- name: Install latest NodeJS using Volta
  ansible.builtin.shell: >
    zsh -i -c "volta install node"
  become_user: "{{ username }}"
  become: true
  args:
    creates: "/home/{{ username }}/.volta/tools/node"

- name: Install latest PNPM using Volta
  ansible.builtin.shell: >
    zsh -i -c "volta install pnpm"
  become_user: "{{ username }}"
  become: true
  args:
    creates: "/home/{{ username }}/.volta/tools/pnpm"

- name: Install homebrew packages
  ansible.builtin.shell: |
    HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_ENV_HINTS=1 /home/linuxbrew/.linuxbrew/bin/brew install \
      bottom \
      broot \
      btop \
      curlie \
      duf \
      dust \
      lazydocker \
      eza \
      fd \
      gh \
      git-quick-stats \
      gping \
      gping \
      httpstat \
      hyperfine \
      lnav \
      oha \
      procs \
      ripgrep \
      sd \
      tealdeer \
      tokei \
      xh \
      yazi

  become_user: "{{ username }}"
  become: true
  args:
    creates: "/home/{{ username }}/.linuxbrew/bin/bottom"

- name: Install Rust tools
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    executable: /bin/bash
  become_user: "{{ username }}"
  become: true
  args:
    creates: "/home/{{ username }}/.cargo/bin/rustc"
