---
- name: Install apt apps - curl, VIm, Terminator, RedShift, htop
  ansible.builtin.apt:
    name:
      - bat
      - curl
      - zip
      - unzip
      - htop
      - libutempter0
      - make
      - shellcheck
      - vim
      - python3-pip
      - jq

# - name: Install SDKMan
#   ansible.builtin.shell: |
#     curl -s "https://get.sdkman.io" | bash
#   become_user: "{{ username }}"
#   become: true

- name: Copy Zscaler root cert to $HOME
  ansible.builtin.copy:
    src: ./defaults/.ZscalerRootCA.crt
    dest: "{{ user_home }}"
    mode: "0644"
  become_user: "{{ username }}"
  become: true

- name: Remove old Volta binary
  ansible.builtin.file:
    path: "{{ user_home }}/.volta/bin/volta"
    state: absent
  become_user: "{{ username }}"

- name: Install Volta
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl https://get.volta.sh | bash
    executable: /usr/bin/zsh
  become_user: "{{ username }}"
  become: true
  args:
    creates: "{{ user_home }}/.volta/bin/volta"

- name: Install latest NodeJS using Volta
  ansible.builtin.shell: >
    zsh -i -c "volta install node"
  become_user: "{{ username }}"
  become: true
  args:
    creates: "{{ user_home }}/.volta/tools/node"

- name: Install latest PNPM using Volta
  ansible.builtin.shell: >
    zsh -i -c "volta install pnpm"
  become_user: "{{ username }}"
  become: true
  args:
    creates: "{{ user_home }}/.volta/tools/pnpm"

- name: Install homebrew packages with ansible community module
  community.general.homebrew:
    name:
      - bottom
      - broot
      - btop
      - curlie
      - duf
      - dust
      - lazydocker
      - eza
      - fd
      - gh
      - git-delta
      - git-quick-stats
      - gping
      - httpstat
      - hyperfine
      - lnav
      - oha
      - procs
      - ripgrep
      - sd
      - tealdeer
      - tokei
      - xh
      - yazi
    state: present
    path: "/home/linuxbrew/.linuxbrew/bin"
  become_user: "{{ username }}"
  become: true

- name: Install Rust tools
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    executable: /bin/bash
  become_user: "{{ username }}"
  become: true
  args:
    creates: "{{ user_home }}/.cargo/bin/rustc"
