---
- name: Install apt apps
  ansible.builtin.apt:
    name:
      - bat
      - curl
      - zip
      - unzip
      - htop
      - libutempter0
      - make
      - tree
      - shellcheck
      - vim
      - python3-pip
      - jq

- name: Install homebrew packages with ansible community module
  vars:
    homebrew_packages:
      - bottom
      - broot
      - btop
      - curlie
      - duf
      - dust
      - lazydocker
      - mdcat
      - eza
      - fd
      - fx
      - gh
      - git-delta
      - git-quick-stats
      - gping
      - httpstat
      - hyperfine
      - lnav
      - oha
      - procs
      - ripgrep
      - sd
      - tealdeer
      - tokei
      - xh
      - yazi
      - yq
  block:
    - name: Install homebrew package
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
        path: "/home/linuxbrew/.linuxbrew/bin"
      become_user: "{{ username }}"
      become: true
      retries: 3
      ignore_errors: true
      register: result
      loop: "{{ homebrew_packages }}"

    - name: Log failed packages
      ansible.builtin.debug:
        msg: "Failed to install package: {{ item.item }}"
      when: item.failed
      loop: "{{ result.results }}"
