---
- name: Install apt apps - curl, VIm, Terminator, RedShift, htop
  ansible.builtin.apt:
    name:
      - guake
      - terminator
      - kcachegrind
      - graphviz

- name: Download and install GitKraken
  block:
    - name: Download GitKraken
      ansible.builtin.get_url:
        url: https://release.axocdn.com/linux/gitkraken-amd64.deb
        dest: "{{ download_dir }}/gitkraken.deb"
    - name: Install GitKraken
      ansible.builtin.apt:
        deb: "{{ download_dir }}/gitkraken.deb"
        force: true

- name: Download and install DBeaver
  block:
    - name: Download DBeaver
      ansible.builtin.get_url:
        url: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
        dest: "{{ download_dir }}/dbeaver.deb"
    - name: Install DBeaver
      ansible.builtin.apt:
        deb: "{{ download_dir }}/dbeaver.deb"
        force: true

- name: Download and install Slack
  block:
    - name: Download Slack page
      ansible.builtin.get_url:
        url: https://slack.com/downloads/instructions/linux?build=deb
        dest: "{{ download_dir }}/slack.html"

    - name: Download latest slack package
      ansible.builtin.shell: |
        grep -oP "https://downloads.+?\.deb" "{{ download_dir }}/slack.html" | xargs wget -O "{{ download_dir }}/slack.deb"
      become_user: "{{ username }}"
      become: true
      args:
        creates: "{{ download_dir }}/slack.deb"

    - name: Install Slack
      ansible.builtin.apt:
        deb: "{{ download_dir }}/slack.deb"
        force: true

- name: Create Terminator config directory path
  ansible.builtin.file:
    dest: "{{ terminator_config_dir }}"
    state: directory
    mode: "0775"
  become_user: "{{ username }}"
  become: true

- name: Configure Terminator
  ansible.builtin.copy:
    src: ./defaults/.config/terminator/config
    dest: "{{ terminator_config_file }}"
    mode: "0644"
  become_user: "{{ username }}"
  become: true

- name: Download and install JetBrains ToolBox
  ansible.builtin.shell: |
    curl -fsSL https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh | bash
  become_user: "{{ username }}"
  become: true
  args:
    creates: "/usr/bin/jetbrains-toolbox"

- name: Download and install Visual Studio Code
  block:
    - name: Download Visual Studio Code
      ansible.builtin.get_url:
        url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
        dest: "{{ download_dir }}/vscode.deb"
    - name: Install Visual Studio Code
      ansible.builtin.apt:
        deb: "{{ download_dir }}/vscode.deb"
        force: true

- name: Install Postman
  ansible.builtin.shell: |
    curl https://gist.githubusercontent.com/SanderTheDragon/1331397932abaa1d6fbbf63baed5f043/raw/postman-deb.sh | sh
  become_user: "{{ username }}"
  become: true
  args:
    creates: "/usr/bin/postman"

- name: Sublime text
  block:
    - name: Install the GPG key
      ansible.builtin.apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg

    - name: Add Sublime Text apt repository
      ansible.builtin.apt_repository:
        repo: "deb [allow-insecure=yes trusted=yes] https://download.sublimetext.com/ apt/stable/"
        filename: sublime-text
        state: present
        update_cache: true

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - apt-transport-https
        state: present
        update_cache: true

    - name: Add sublime text
      ansible.builtin.apt:
        update_cache: true
        name:
          - sublime-text
