---
- name: Install apt apps - curl, VIm, Terminator, RedShift, htop
  ansible.builtin.apt:
    name:
      - bat
      - curl
      - zip
      - unzip
      - htop
      - libutempter0
      - make
      - shellcheck
      - vim
      - python3-pip
      - jq

# - name: Install SDKMan
#   ansible.builtin.shell: |
#     curl -s "https://get.sdkman.io" | bash
#   become_user: "{{ username }}"

- name: Copy Zscaler root cert to $HOME
  ansible.builtin.copy:
    src: ./defaults/ZscalerRootCA.crt
    dest: "{{ user_home }}"
    mode: '0644'
  become_user: "{{ username }}"

- name: Install Volta
  ansible.builtin.shell: |
    curl https://get.volta.sh | bash
  become_user: "{{ username }}"

- name: Install latest NodeJS using Volta
  ansible.builtin.shell: >
    zsh -i -c "volta install node"
  become_user: "{{ username }}"

- name: Install latest PNPM using Volta
  ansible.builtin.shell: >
    zsh -i -c "volta install pnpm"
  become_user: "{{ username }}"

- name: Install homebrew packages
  ansible.builtin.shell: |
    brew install hyperfine fd sd ripgrep dust duf bottom curlie oha gping
  become_user: "{{ username }}"
