---
- name: Install apt apps - curl, VIm, Terminator, RedShift, htop
  ansible.builtin.apt:
    name:
      - bat
      - curl
      - zip
      - unzip
      - htop
      - libutempter0
      - make
      - tree
      - shellcheck
      - vim
      - python3-pip
      - jq

- name: Copy Zscaler root cert to $HOME
  ansible.builtin.copy:
    src: ./defaults/.ZscalerRootCA.crt
    dest: "{{ user_home }}"
    mode: "0644"
  become_user: "{{ username }}"
  become: true

- name: Install homebrew packages with ansible community module
  community.general.homebrew:
    name:
      - bottom
      - broot
      - btop
      - curlie
      - duf
      - dust
      - lazydocker
      - eza
      - fd
      - gh
      - git-delta
      - git-quick-stats
      - gping
      - httpstat
      - hyperfine
      - lnav
      - oha
      - procs
      - ripgrep
      - sd
      - tealdeer
      - tokei
      - xh
      - yazi
    state: latest
    upgrade_all: true
    path: "/home/linuxbrew/.linuxbrew/bin"
  become_user: "{{ username }}"
  become: true
