---
- name: Install apt apps - curl, VIm, Terminator, RedShift, htop
  ansible.builtin.apt:
    name:
      - guake
      - terminator
      - kcachegrind
      - graphviz

- name: Download and install GitKraken
  block:
    - name: Download GitKraken
      ansible.builtin.get_url:
        url: https://release.axocdn.com/linux/gitkraken-amd64.deb
        dest: "{{ download_dir }}/gitkraken.deb"
    - name: Install GitKraken
      ansible.builtin.apt:
        deb: "{{ download_dir }}/gitkraken.deb"
        force: true

- name: Download and install DBeaver
  block:
    - name: Download DBeaver
      ansible.builtin.get_url:
        url: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
        dest: "{{ download_dir }}/dbeaver.deb"
    - name: Install DBeaver
      ansible.builtin.apt:
        deb: "{{ download_dir }}/dbeaver.deb"
        force: true

# TODO: Make this a task and pass it the URL
- name: Download and install Slack
  block:
    - name: Download Slack page
      ansible.builtin.get_url:
        url: https://slack.com/intl/en-rs/downloads/instructions/ubuntu
        dest: "{{ download_dir }}/slack.html"

    - name: Download latest slack package
      ansible.builtin.shell: |
        URL=https://downloads.slack-edge.com/releases/linux/;
        FILE_NAME=$(grep -oP  "(slack-desktop)-([0-9]+\.[0-9]+\.[0-9]+)-(amd64.deb)" "{{ download_dir }}/slack.html" | head -n 1 );
        VERSION=$(echo $FILE_NAME | egrep -o "[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}");
        echo $URL$VERSION/prod/x64/$FILE_NAME | xargs wget -O "{{ download_dir }}/slack.deb"
    - name: Install Slack
      ansible.builtin.apt:
        deb: "{{ download_dir }}/slack.deb"
        force: true

- name: Create Terminator config directory path
  ansible.builtin.file:
    dest: "{{ terminator_config_dir }}"
    state: directory
    mode: "0775"
  become_user: "{{ username }}"

- name: Configure Terminator
  ansible.builtin.copy:
    src: ./defaults/.config/terminator/config
    dest: "{{ terminator_config_file }}"
    mode: "0644"
  become_user: "{{ username }}"

- name: Download and install JetBrains ToolBox
  ansible.builtin.shell: |
    curl -fsSL https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh | bash
  become_user: "{{ username }}"

- name: Download and install Visual Studio Code
  block:
    - name: Download Visual Studio Code
      ansible.builtin.get_url:
        url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
        dest: "{{ download_dir }}/vscode.deb"
    - name: Install Visual Studio Code
      ansible.builtin.apt:
        deb: "{{ download_dir }}/vscode.deb"
        force: true

- name: Install Postman
  ansible.builtin.shell: curl https://gist.githubusercontent.com/SanderTheDragon/1331397932abaa1d6fbbf63baed5f043/raw/postman-deb.sh | sh
  become_user: "{{ username }}"

- name: Sublime text
  block:
    - name: Install the GPG key
      ansible.builtin.apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg

    - name: Add apt repository
      ansible.builtin.shell: |
        echo "deb [allow-insecure=yes trusted=yes] https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list

    - name: Install dependencies
      ansible.builtin.shell: |
        apt install -y ca-certificates apt-transport-https

    - name: Add sublime text
      ansible.builtin.apt:
        update_cache: true
        name:
          - sublime-text
