---
- name: Install apt apps - sysfsutils
  apt:
    name:
      - sysfsutils

- name: Add support for Xbox One S controller bluetooth connection
  lineinfile:
    path: "{{ sysfs }}"
    line: /module/bluetooth/parameters/disable_ertm=1
