---
- name: Install apt apps - sysfsutils
  ansible.builtin.apt:
    name:
      - sysfsutils

- name: Add support for Xbox One S controller bluetooth connection
  ansible.builtin.lineinfile:
    path: "{{ sysfs }}"
    line: /module/bluetooth/parameters/disable_ertm=1
