---
- name: Download and install RescueTime
  block:
    - name: Download RescueTime
      get_url:
        url: https://www.rescuetime.com/installers/rescuetime_current_amd64.deb
        dest: /tmp/rescuetime.deb
    - name: Install RescueTime
      apt:
        deb: /tmp/rescuetime.deb
  when: "'rescuetime' not in ansible_facts.packages"

- name: Download and install Google Chrome
  block:
    - name: Download Google Chrome
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb
    - name: Install Google Chrome
      apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb
  when: "'google-chrome' not in ansible_facts.packages"

- name: Download and install Zoom
  block:
    - name: Download Zoom
      get_url:
        url: https://zoom.us/client/latest/zoom_amd64.deb
        dest: /tmp/zoom_amd64.deb
    - name: Install Zoom
      apt:
        deb: /tmp/zoom_amd64.deb
  when: "'zoom' not in ansible_facts.packages"

- name: Download and install Viber
  block:
    # - name: Download dependencies
    #   get_url:
    #     url: http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb
    #     dest: /tmp/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb
    # - name: Install dependencies
    #   apt:
    #     deb: /tmp/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb
    - name: Download Viber
      get_url:
        url: https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
        dest: /tmp/viber.deb
    - name: Install Viber
      apt:
        deb: /tmp/viber.deb
  when: "'viber' not in ansible_facts.packages"

- name: Download and install Tixati
  block:
    - name: Download Tixati
      get_url:
        url: https://download2.tixati.com/download/tixati_2.72-1_amd64.deb
        dest: /tmp/tixati.deb
    - name: Install Tixati
      apt:
        deb: /tmp/tixati.deb
  when: "'tixati' not in ansible_facts.packages"

- name: Set Tixati as default torrent client
  shell: |
    gio mime x-scheme-handler/magnet tixati.desktop
  when: ansible_distribution == 'Linux Mint' and ansible_distribution_major_version == '19'

- name: Download and install UnifiedRemote
  block:
    - name: Download UnifiedRemote
      get_url:
        url: https://www.unifiedremote.com/download/linux-x64-deb
        dest: /tmp/uremote.deb
    - name: Install UnifiedRemote
      apt:
        deb: /tmp/uremote.deb
  when: "'urserver' not in ansible_facts.packages"

- name: Install apt apps - Variety, Flameshot, Bleachbit
  apt:
    name:
      - bleachbit
      - fd-find
      - flameshot
      - fzf
      - httpie
      - ncdu
      - papirus-icon-theme
      - peco
      - silversearcher-ag
      - thefuck
      - tlp
      - unzip
      - variety

- name: Install snap apps (classic) - Skype
  snap:
    name:
      - skype
      - slack
    classic: yes

- name: Install snap apps - Firefox, Mailspring, VLC
  snap:
    name:
      - firefox
      - mailspring
      - onlyoffice-desktopeditors
      - vlc

- name: Remove apt copies
  apt:
    state: absent
    name:
      - vlc
      - firefox
    purge: yes

- name: "Create {{ LOCAL_BIN }} directory"
  file:
    path: "{{ LOCAL_BIN }}"
    state: directory
  become_user: "{{ USERNAME }}"

- name: Copy theme-by-time.sh script
  copy:
    src: "./defaults/scripts/theme-by-time.sh"
    dest: "{{ LOCAL_BIN }}"
    mode: u+x
  become_user: "{{ USERNAME }}"
