---
- name: Download and install RescueTime
  block:
    - name: Download RescueTime
      get_url:
        url: https://www.rescuetime.com/installers/rescuetime_current_amd64.deb
        dest: "{{ DOWNLOAD_DIR}}/rescuetime.deb"
    - name: Install RescueTime
      apt:
        deb: "{{ DOWNLOAD_DIR}}/rescuetime.deb"

- name: Download and install Google Chrome
  block:
    - name: Download Google Chrome
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: "{{ DOWNLOAD_DIR}}/google-chrome-stable_current_amd64.deb"
    - name: Install Google Chrome
      apt:
        deb: "{{ DOWNLOAD_DIR}}/google-chrome-stable_current_amd64.deb"

- name: Download and install Zoom
  block:
    - name: Download Zoom
      get_url:
        url: https://zoom.us/client/latest/zoom_amd64.deb
        dest: "{{ DOWNLOAD_DIR}}/zoom_amd64.deb"
    - name: Install Zoom
      apt:
        deb: "{{ DOWNLOAD_DIR}}/zoom_amd64.deb"

- name: Download and install Viber
  block:
    # - name: Download dependencies
    #   get_url:
    #     url: http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb
    #     dest: /tmp/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb
    # - name: Install dependencies
    #   apt:
    #     deb: /tmp/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb
    - name: Download Viber
      get_url:
        url: https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
        dest: "{{ DOWNLOAD_DIR}}/viber.deb"
    - name: Install Viber
      apt:
        deb: "{{ DOWNLOAD_DIR}}/viber.deb"

- name: Download and install Tixati
  block:
    - name: Download Tixati page
      get_url:
        url: https://www.tixati.com/download/linux.html
        dest: "{{ DOWNLOAD_DIR}}/tixati.html"
    - name: Find out latest Tixati URL
      shell: |
        grep  -oP "<a href=(.+amd64.deb)\">" "{{ DOWNLOAD_DIR}}/tixati.html" | grep -oP  "http.+amd64.deb"  | xargs wget -O "{{ DOWNLOAD_DIR}}/tixati.deb"
    - name: Install Tixati
      apt:
        deb: "{{ DOWNLOAD_DIR}}/tixati.deb"

- name: Set Tixati as default torrent client
  shell: |
    gio mime x-scheme-handler/magnet tixati.desktop
  when: ansible_distribution == 'Linux Mint'

- name: Download and install UnifiedRemote
  block:
    - name: Download UnifiedRemote
      get_url:
        url: https://www.unifiedremote.com/download/linux-x64-deb
        dest: "{{ DOWNLOAD_DIR}}/uremote.deb"
    - name: Install UnifiedRemote
      apt:
        deb: "{{ DOWNLOAD_DIR}}/uremote.deb"

- name: Add Folder color nemo repo
  shell: |
    add-apt-repository ppa:costales/folder-color -y

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install apt apps - Variety, Flameshot, Bleachbit
  apt:
    name:
      - bleachbit
      - fd-find
      - flameshot
      - folder-color-nemo
      - fzf
      - httpie
      - ncdu
      - papirus-icon-theme
      - peco
      - slack-desktop
      - silversearcher-ag
      - thefuck
      - tlp
      - unzip
      - variety

- name: Install snap apps (classic) - Skype
  snap:
    name:
      - skype
    classic: yes

- name: Install snap apps - Firefox, Mailspring, VLC
  snap:
    name:
      - firefox
      - mailspring
      - onlyoffice-desktopeditors
      - vlc

- name: Remove apt copies
  apt:
    state: absent
    name:
      - vlc
      - firefox
    purge: yes

- name: "Create {{ LOCAL_BIN }} directory"
  file:
    path: "{{ LOCAL_BIN }}"
    state: directory
  become_user: "{{ USERNAME }}"

- name: Copy theme-by-time.sh script
  copy:
    src: "./defaults/scripts/theme-by-time.sh"
    dest: "{{ LOCAL_BIN }}"
    mode: u+x
  become_user: "{{ USERNAME }}"
