---
- name: Install apt apps
  ansible.builtin.apt:
    name:
      - httpie
      - ncdu
      - peco
      - thefuck
      - tlp
      - unzip

- name: Install homebrew packages with ansible community module
  community.general.homebrew:
    name:
      - fzf
      - eza
      - lsd
      - neovim
      - helix
    state: latest
    upgrade_all: true
    path: "/home/linuxbrew/.linuxbrew/bin"
  become_user: "{{ username }}"
  become: true
