---
- name: Install apt apps
  ansible.builtin.apt:
    name:
      - httpie
      - ncdu
      - peco
      - thefuck
      - tlp
      - unzip

- name: Install homebrew packages
  ansible.builtin.shell: |
    HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_ENV_HINTS=1 /home/linuxbrew/.linuxbrew/bin/brew install fzf eza
  become_user: "{{ username }}"
  become: true
