---

- name: Install apt apps
  ansible.builtin.apt:
    name:
      - httpie
      - ncdu
      - peco
      - thefuck
      - tlp
      - unzip

- name: Download and install fzf
  ansible.builtin.include_tasks: install_github_asset.yaml
  vars:
    github_repo: junegunn/fzf
    github_asset: fzf
    type: tar.gz


- name: Download and install eza
  ansible.builtin.include_tasks: install_github_asset.yaml
  vars:
    github_repo: eza-community/eza
    github_asset: eza
    type: tar.gz
