---
- name: Install apt apps
  ansible.builtin.apt:
    name:
      - httpie
      - ncdu
      - peco
      - thefuck
      - tlp
      - unzip

- name: Install homebrew packages with ansible community module
  community.general.homebrew:
    name:
      - fzf
      - eza
      - lsd
    state: present
  become_user: "{{ username }}"
  become: true
