---

- name: Install apt apps
  ansible.builtin.apt:
    name:
      - fzf
      - httpie
      - ncdu
      - peco
      - thefuck
      - tlp
      - unzip

- name: Install and install input-remapper
  block:
    - ansible.builtin.include_tasks: download_github_asset.yaml
      vars:
        github_repo: sezanzeb/input-remapper
        github_asset: input-remapper
        github_asset_dest: "{{ download_dir }}/input-remapper"
        type: deb

    - name: Install input-remapper
      ansible.builtin.apt:
        deb: "{{ download_dir }}/input-remapper.deb"
        force: true
