---
- name: Install SDKMan
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -s "https://get.sdkman.io" | bash
    executable: "{% if ansible_os_family == 'Darwin' %}/bin/bash{% else %}/usr/bin/bash{% endif %}"
  become_user: "{{ username }}"
  become: true
  register: sdkman_install
  changed_when: sdkman_install.rc == 0
