---
- name: Install Volta
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl https://get.volta.sh | bash
    executable: /usr/bin/bash
  become_user: "{{ username }}"
  become: true
  register: volta_install
  changed_when: volta_install.rc == 0

- name: Generate Volta completions
  ansible.builtin.shell: >
    zsh -i -c "volta completions zsh > ~/.zsh/completions/_volta"
  become_user: "{{ username }}"
  become: true
  register: volta_completions
  changed_when: volta_completions.rc == 0

- name: Install latest NodeJS using Volta
  ansible.builtin.shell: >
    zsh -i -c "volta install node@20"
  become_user: "{{ username }}"
  become: true
  register: node_install
  changed_when: node_install.rc == 0
  retries: 3

- name: Install latest PNPM using Volta
  ansible.builtin.shell: >
    zsh -i -c "volta install pnpm@9"
  become_user: "{{ username }}"
  become: true
  register: pnpm_install
  changed_when: pnpm_install.rc == 0
  retries: 3
