---
- name: Remove nosnap file
  ansible.builtin.file:
    path: /etc/apt/preferences.d/nosnap.pref
    state: absent

- name: Add support for snap apps
  ansible.builtin.apt:
    name:
      - snapd
    update_cache: true

- name: "Add {{ snap_bin_path }} to environment PATH"
  ansible.builtin.lineinfile:
    dest: /etc/environment
    state: present
    backrefs: true
    regexp: 'PATH=([\"]*)((?!.*?{{ snap_bin_path }}).*?)(["]*)$'
    line: PATH=\1\2:{{ snap_bin_path }}\3
