---
- name: Add support for snap apps
  apt:
    name:
      - snapd

- name: "Add {{ SNAP_BIN_PATH }} to environment PATH"
  lineinfile:
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: 'PATH=([\"]*)((?!.*?{{ SNAP_BIN_PATH }}).*?)(["]*)$'
    line: PATH=\1\2:{{ SNAP_BIN_PATH }}\3
