---
- name: Add support for snap apps
  apt:
    name:
      - snapd

- name: Add snap to current user PATH
  lineinfile:
    path: "{{ PROFILE }}"
    line: PATH=/snap/bin:$PATH
    insertafter: EOF
