---
- name: Download themes from Cinnamon Spices
  block:
    - name: Create themes directory
      file:
        dest: "{{ themes }}"
        state: directory
        mode: 0775
      become_user: "{{ username }}"

    - name: Download Adapta-Nokto
      get_url:
        url: https://cinnamon-spices.linuxmint.com/files/themes/Adapta-Nokto.zip
        dest: "{{ download_dir }}/Adapta-Nokto.zip"

    - name: Move theme in to {{ themes }}
      unarchive:
        src: "{{ download_dir }}/Adapta-Nokto.zip"
        dest: "{{ themes }}"
        owner: "{{ username }}"
        remote_src: true

    - name: Download Adapta
      get_url:
        url: https://cinnamon-spices.linuxmint.com/files/themes/Adapta.zip
        dest: "{{ download_dir }}/Adapta.zip"

    - name: Move theme in to {{ themes }}
      unarchive:
        src: "{{ download_dir }}/Adapta.zip"
        dest: "{{ themes }}"
        owner: "{{ username }}"
        remote_src: true

    - name: Install Arc Dark theme
      apt:
        name: arc-theme
        state: present

    - name: Set up theme changer autostart
      copy:
        src: ./defaults/.config/autostart/theme_changer.desktop
        dest: "{{ autostart_path }}"
        mode: 0664
      become_user: "{{ username }}"
