---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade APT applications
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Create "{{ download_dir }}
  ansible.builtin.file:
    dest: "{{ download_dir }}"
    state: directory
    mode: "0777"

- name: Get OS facts
  ansible.builtin.setup:
    gather_subset:
      - all

- name: Read /etc/os-release file
  ansible.builtin.slurp:
    src: /etc/os-release
  register: os_release_file

- name: Set ubuntu_codename fact
  ansible.builtin.set_fact:
    ubuntu_codename: "{{ os_release_file['content'] | b64decode | regex_search('UBUNTU_CODENAME=(.*)', '\\1') }}"

- name: Print ubuntu_codename fact
  ansible.builtin.debug:
    msg: "Ubuntu codename is {{ ubuntu_codename }}"
