---
- name: Update APT cache
  apt:
    update_cache: true

- name: Create "{{ download_dir }}
  file:
    dest: "{{ download_dir }}"
    state: directory
    mode: 0775

- name: Get Ubuntu code name
  shell: |
    grep UBUNTU /etc/os-release  | grep -E -o "=.+" | grep -E -o '[^=].+'
  register: ubuntu_codename
- name: set fact
  set_fact:
    ubuntu_codename: "{{ ubuntu_codename.stdout }}"
