---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade APT applications
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Create "{{ download_dir }}
  ansible.builtin.file:
    dest: "{{ download_dir }}"
    state: directory
    mode: "0777"

- name: Get OS facts
  ansible.builtin.setup:
    gather_subset:
      - all

- name: Set ubuntu_codename fact
  ansible.builtin.set_fact:
    ubuntu_codename: "{{ ansible_lsb.codename }}"
