---
- name: Install openconnect for gnome
  apt:
    name:
      - network-manager-openconnect
      - network-manager-openconnect-gnome

- name: Install L2TP VPN client
  apt:
    name:
      - network-manager-l2tp
      - network-manager-l2tp-gnome
