---
- name: Install zsh
  ansible.builtin.apt:
    name: zsh

- name: Save ZSH install location into a variable
  ansible.builtin.command: which zsh
  register: zsh_install_path
  changed_when: false

- name: Set ZSH as default login shell for current user
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "{{ zsh_install_path.stdout }}"

- name: Initialize .zshrc
  ansible.builtin.copy:
    src: ./defaults/.zshrc
    dest: "{{ zshrc }}"
    mode: "0644"
  become_user: "{{ username }}"
  become: true

- name: Create ~/.zsh/completions directory
  ansible.builtin.file:
    path: "{{ user_home }}/.zsh/completions"
    state: directory
    mode: "0755"
  become_user: "{{ username }}"
  become: true

- name: Copy .p10k.zsh
  ansible.builtin.copy:
    src: ./defaults/.p10k.zsh
    dest: "{{ user_home }}"
    mode: "0644"
  become_user: "{{ username }}"
  become: true

- name: Install antidote (ZSH plugin manager)
  block:
    - name: Ensure antidote directory exists
      ansible.builtin.file:
        path: "{{ user_home }}/.antidote"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"
      become_user: "{{ username }}"

    - name: Clone antidote repository
      ansible.builtin.git:
        repo: https://github.com/mattmc3/antidote.git
        dest: "{{ user_home }}/.antidote"
        depth: 1
        force: true
        version: master
      become_user: "{{ username }}"

- name: Configure antidote
  block:
    - name: Copy .zsh_plugins.sh
      ansible.builtin.copy:
        src: ./defaults/.zsh_plugins.sh
        dest: "{{ user_home }}/.zsh_plugins.sh"
        mode: "0644"
      become_user: "{{ username }}"

    - name: Download antidote bundles
      ansible.builtin.shell: |
        . /etc/zsh/zshenv
        antidote bundle <~/.zsh_plugins.sh >~/.zsh_plugins.zsh
      args:
        executable: /bin/zsh
        creates: "{{ user_home }}/.zsh_plugins.zsh"
      become_user: "{{ username }}"
