---
- name: Install zsh
  apt:
    name: zsh

- name: Save ZSH install location into a variable
  shell: which zsh
  register: zsh_install_path

- name: Set ZSH as default login shell for current user
  user:
    name: "{{ username }}"
    shell: "{{ zsh_install_path.stdout }}"

- name: Download and install antidote - ZSH plugin manager
  block:
    - name: Download antidote
      shell: |
        zsh -c "cd ~ && git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-~}/.antidote"
      become_user: "{{ username }}"

- name: Configure antidote
  block:
    - name: Copy .zsh_plugins.txt
      copy:
        src: ./defaults/.zsh_plugins.txt
        dest: "{{ user_home }}"
        mode: 0644
      become_user: "{{ username }}"

    - name: Download antidote bundles from .zsh_plugins.txt
      shell:
        cmd: antidote bundle <~/.zsh_plugins.txt >~/.zsh_plugins.zsh
      become_user: "{{ username }}"

- name: Copy .p10k.zsh
  copy:
    src: ./defaults/.p10k.zsh
    dest: "{{ user_home }}"
    mode: 0644
  become_user: "{{ username }}"

- name: Initialize .zshrc
  copy:
    src: ./defaults/.zshrc
    dest: "{{ zshrc }}"
    mode: 0644
  become_user: "{{ username }}"
