---
- name: Install zsh
  apt:
    name: zsh

- name: Save ZSH install location into a variable
  shell: which zsh
  register: zsh_install_path
  become_user: "{{ USERNAME}}"

- name: Set ZSH as default login shell for current user
  user:
    name: "{{ USERNAME}}"
    shell: "{{ zsh_install_path.stdout }}"

- name: Install antigen - ZSH plugin manager
  get_url:
    url: https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh
    dest: "/home/{{ USERNAME }}/antigen.zsh"

- name: Intialize .zshrc
  copy:
    src: ./defaults/.zshrc
    dest: "/home/{{ USERNAME }}"
