---
- name: Install zsh
  apt:
    name: zsh

- name: Save ZSH install location into a variable
  shell: which zsh
  register: zsh_install_path

- name: Set ZSH as default login shell for current user
  user:
    name: "{{ USERNAME}}"
    shell: "{{ zsh_install_path.stdout }}"

- name: Download and install antibody - ZSH plugin manager
  block:
    - name: Download antibody
      get_url:
        url: https://git.io/antibody
        dest: "{{ ANTIBODY_FILE_PATH }}"
      become_user: "{{ USERNAME }}"

    - name: Install antibody
      shell:
        cmd: sh "{{ ANTIBODY_FILE_PATH }}" -b /usr/local/bin

- name: Configure antibody
  block:
    - name: Copy .zsh_plugins_antibody.pl
      copy:
        src: ./defaults/.zsh_plugins_antibody.pl
        dest: "{{ USER_HOME }}"
      become_user: "{{ USERNAME }}"

    - name: Remove old antibody bundles
      file:
        path: ~/.cache/antibody
        state: absent
      become_user: "{{ USERNAME}}"

    - name: Download antibody bundles from .zsh_plugins_antibody.pl
      shell:
        cmd: antibody bundle < ~/.zsh_plugins_antibody.pl > ~/.zsh_plugins_antibody.sh
      become_user: "{{ USERNAME}}"

- name: Copy .p10k.zsh
  copy:
    src: ./defaults/.p10k.zsh
    dest: "{{ USER_HOME }}"
  become_user: "{{ USERNAME }}"

- name: Initialize .zshrc
  copy:
    src: ./defaults/.antibody.zshrc
    dest: "{{ ZSHRC }}"
  become_user: "{{ USERNAME }}"

- name: "Add nvm lazy load binaries to zshenv"
  lineinfile:
    dest: /etc/zsh/zshenv
    state: present
    line: export NVM_LAZY_LOAD_EXTRA_COMMANDS=('vim' 'nvim' 'code' 'java')
