---
- name: Install zsh
  apt:
    name: zsh

- name: Save ZSH install location into a variable
  shell: which zsh
  register: zsh_install_path

- name: Set ZSH as default login shell for current user
  user:
    name: "{{ USERNAME}}"
    shell: "{{ zsh_install_path.stdout }}"

# Deprecated. Replatec with antibody below, for performance reasons
- name: Install antigen - ZSH plugin manager
  get_url:
    url: https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh
    dest: "/home/{{ USERNAME }}/antigen.zsh"
    owner: "{{ USERNAME}}"
    mode: 0644

- name: Download and install antibody - ZSH plugin manager
  block:
    - name: Download antibody
      get_url:
        url: https://git.io/antibody
        dest: "/home/{{ USERNAME }}/antibody.sh"
        owner: "{{ USERNAME}}"
        mode: 0644

    - name: Install antibody
      shell:
        cmd: sh "/home/{{ USERNAME }}/antibody.sh" -b /usr/local/bin

- name: Configure antibody
  block:
    - name: Copy .zsh_plugins_antibody.pl
      copy:
        src: ./defaults/.zsh_plugins_antibody.pl
        dest: "/home/{{ USERNAME }}"
        owner: "{{ USERNAME}}"
        mode: 0644

    - name: Download antibody bundles from .zsh_plugins_antibody.pl
      shell:
        cmd: antibody bundle < ~/.zsh_plugins_antibody.pl > ~/.zsh_plugins_antibody.sh
      become_user: "{{ USERNAME}}"

- name: Download powerlevel10k zsh theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    depth: "1"
    dest: "~/powerlevel10k"
  become_user: "{{ USERNAME }}"

- name: Initialize .zshrc
  copy:
    src: ./defaults/.antibody.zshrc
    dest: "/home/{{ USERNAME }}/.zshrc"
    owner: "{{ USERNAME}}"
    mode: 0644
