---
- name: Install zsh
  apt:
    name: zsh

- name: Save ZSH install location into a variable
  shell: which zsh
  register: zsh_install_path

- name: Set ZSH as default login shell for current user
  user:
    name: "{{ username }}"
    shell: "{{ zsh_install_path.stdout }}"

- name: Download and install antibody - ZSH plugin manager
  block:
    - name: Download antibody
      get_url:
        url: https://git.io/antibody
        dest: "{{ antibody_file_path }}"
      become_user: "{{ username }}"

    - name: Install antibody
      shell:
        cmd: sh "{{ antibody_file_path }}" -b /usr/local/bin

- name: Configure antibody
  block:
    - name: Copy .zsh_plugins_antibody.pl
      copy:
        src: ./defaults/.zsh_plugins_antibody.pl
        dest: "{{ user_home }}"
        mode: 0644
      become_user: "{{ username }}"

    - name: Remove old antibody bundles
      file:
        path: ~/.cache/antibody
        state: absent
      become_user: "{{ username }}"

    - name: Download antibody bundles from .zsh_plugins_antibody.pl
      shell:
        cmd: antibody bundle < ~/.zsh_plugins_antibody.pl > ~/.zsh_plugins_antibody.sh
      become_user: "{{ username }}"

- name: Copy .p10k.zsh
  copy:
    src: ./defaults/.p10k.zsh
    dest: "{{ user_home }}"
    mode: 0644
  become_user: "{{ username }}"

- name: Initialize .zshrc
  copy:
    src: ./defaults/.antibody.zshrc
    dest: "{{ zshrc }}"
    mode: 0644
  become_user: "{{ username }}"
