---
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "docs/**/*"
      - ".github/workflows/documentation.yaml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          version: latest
          install: true

      - name: Install dependencies
        run: cd docs && pnpm install --frozen-lockfile

      - name: Build the documentation
        run: cd docs && npx nuxt build --preset github_pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.output/public
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
