---
name: macOS
on:
  push:
    branches:
      - master
    paths:
      - "post-installation/**/*"
      - ".github/workflows/macos.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "post-installation/**/*"
      - ".github/workflows/macos.yaml"
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00

concurrency:
  group: github-api-rate-limit-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ansible:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          brew install ansible

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install -r requirements.yaml

      - name: Run ansible playbook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}
          ansible-playbook ./playbook_macos.yaml -e username=$(whoami) -e all=true -e github_token=$GITHUB_TOKEN
