---
name: WSL
on:
  push:
    branches:
      - master
    paths:
      - "post-installation/**/*"
      - ".github/workflows/wsl.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "post-installation/**/*"
      - ".github/workflows/wsl.yaml"
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ansible:
    runs-on: windows-latest
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: Vampire/setup-wsl@v4
        with:
          wsl-shell-user: test
          distribution: Ubuntu-24.04
          wsl-version: 2
          set-as-default: "true"
          update: "false"
          additional-packages: ansible

      # Set password for test user
      - shell: wsl-bash -u root {0}
        run: echo "test:testpw" | chpasswd

      # Add test user to sudo group
      - shell: wsl-bash -u root {0}
        run: usermod -a -G sudo test

      # Checkout the current repository code
      - uses: actions/checkout@v4

      # Copy the repository to WSL user home directory
      - shell: wsl-bash {0}
        run: |
          WORKSPACE_PATH=$(wslpath "${{ github.workspace }}")
          cp -r "$WORKSPACE_PATH" /home/test/ansible-post-installation

      - shell: wsl-bash {0}
        run: cd /home/test/ansible-post-installation && echo "testpw" > .github/workflows/ansible_become_password.txt

      - shell: wsl-bash {0}
        run: chmod 600 /home/test/ansible-post-installation/.github/workflows/ansible_become_password.txt

      - shell: wsl-bash {0}
        run: ls -la /home/test/ansible-post-installation/.github/workflows

      - name: Install Ansible collections
        shell: wsl-bash {0}
        run: |
          cd /home/test/ansible-post-installation/ && ansible-galaxy collection install -r requirements.yaml

      - name: Run ansible playbook
        shell: wsl-bash {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /home/test/ansible-post-installation/
          ansible-playbook ./playbook.yaml \
            --become-password-file .github/workflows/ansible_become_password.txt \
            -e username=$(whoami) \
            -e all=true \
            -e github_token="$GITHUB_TOKEN"
