name: Run ansible playbook on WSL
on:
  push:
    branches:
      - master
    paths:
      - "post-installation/**/*"
      - ".github/workflows/wsl.yml"
  pull_request:
    branches:
      - master
    paths:
      - "post-installation/**/*"
      - ".github/workflows/wsl.yml"
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ansible:
    runs-on: windows-latest
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: Vampire/setup-wsl@v4
        with:
          wsl-shell-user: test
          distribution: Ubuntu-24.04
          wsl-version: 2
          set-as-default: "true"
          update: "false"
          additional-packages: ansible
            unzip

      - uses: actions/checkout@v4

      - shell: wsl-bash -u root {0}
        run: echo "test:testpw" | chpasswd

      - shell: wsl-bash -u root {0}
        run: usermod -a -G sudo test

      - shell: wsl-bash -u root {0}
        run: cd /mnt/d/a/ansible-post-installation && chown test:test -R  .

      - run: pwd

      - run: ls -la

      - run: echo testpw > ansible_become_password.txt

      - shell: wsl-bash -u root {0}
        run: chmod 666 ansible_become_password.txt

      - run: ls -la ansible_become_password.txt

      - name: Run ansible playbook
        run: |
          ansible-playbook ./playbook.yml --become-password-file ansible_become_password.txt -e username=$(whoami) -e all=true
