name: Run ansible playbook on WSL
on:
  push:
    branches:
      - master
    paths:
      - 'post-installation/**/*'
      - '.github/workflows/build-wsl.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'post-installation/**/*'
      - '.github/workflows/build-wsl.yml'
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ansible:
      runs-on: windows-latest
      defaults:
        run:
            shell: wsl-bash {0}
      steps:

          - uses: Vampire/setup-wsl@v4
            with:
              wsl-shell-user: test
              distribution: Ubuntu-24.04
              wsl-version: 2
              set-as-default: 'true'
              update: 'false'
              additional-packages:
                ansible
                unzip

          - uses: actions/checkout@v4

          - run: echo $USER

          - run: pwd

          - run: ls -la

          - name: Run ansible playbook
            run: |
              ansible-playbook ./playbook.yml -K -e username=$(whoami) -e all=true
